In [1]:
import numpy as np

In [2]:
def identity_function(x): 
    return x 

In [10]:
def sigmoid_function(x): 
    output = 1 / 1+ np.exp(-x)
    return output 

In [13]:
def relu_function(x):
    return np.maximum(0,x) 

In [57]:
np.random.rand(3,)

array([0.48038841, 0.84806343, 0.27139341])

In [49]:
np.array([1,2,3])

array([1, 2, 3])

In [63]:
np.random.rand(3,2)

array([[0.28026079, 0.73345025],
       [0.56725421, 0.66006798],
       [0.18733912, 0.9295499 ]])

In [64]:
def init_network(): 
    network = {} 
    network["W1"] = np.random.rand(2,3)
    network["b1"] = np.random.rand(3,)
    network["W2"] = np.random.rand(3,3)
    network["b2"] = np.random.rand(3,)
    network["W3"] = np.random.rand(3,2)
    network["b3"] = np.random.rand(2,)

    return network
    
def feed_forward(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b3"], network["b3"] 

    a1 = np.dot(x,W1) + b1 
    print(a1.shape)
    z1 = sigmoid_function(a1)
    print(z1.shape) 
    a2 = np.dot(z1,W2) + b2
    print(a2.shape) 
    z2 = sigmoid_function(a2) 
    a3 = np.dot(z2,W3) + b3 
    y = identity_function(a3)

    return y

x = np.random.rand(1,2)
net = init_network() 
output = feed_forward(net,x)

(1, 3)
(1, 3)


ValueError: operands could not be broadcast together with shapes (1,3) (2,) 